import Head from 'next/head'
import NavbarComponents from "@/components/Navbar"
import BodyComponents from '@/components/Body'
import FooterComponents from '@/components/Footer'
import { GetServerSideProps, NextPageContext } from 'next'
import Success from '@/components/Success'

export default function Home(props: any) {
    console.log(props)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Success title={props.data.proute}/>
      </main>
    </>
  )
}

export async function getServerSideProps(context: NextPageContext) {

    const data = context.query

    return { props: { data } }
}

